version: '3'

services:

# MYSQL #

  phonebook-mysql:
    container_name: phone-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password       
    volumes:
      - ./db_data:/var/lib/mysql  
    restart: "no"
    networks:
      - agenda 

# APP #

  phonebook-app:
    container_name: phone-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
    ports:
      - "8100:8181"
    restart: "no"
    networks:
      - agenda 

# PHPMYADMIN #             
       
  phonebook-pma:
    container_name: phone-pma
    image: phpmyadmin/phpmyadmin     
    depends_on:      
      - phonebook-mysql
    ports:      
      - "8180:80"    
    restart: "no"   
    environment:
     - PMA_ARBITRARY=1 
     - PMA_HOST=phone-mysql
     - PMA_USER=dev 
     - PMA_PASSWORD=dev 
    networks:
      - agenda 
    
volumes:
  db_data:

networks:
  agenda:     



